apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rookeval-claim
  labels:
    app: eval
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
