apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-eval
  namespace: rook
spec:
  versionTag: master
  dataDirHostPath: "/var/lib/docker/rook-eval"
  hostNetwork: false
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: nvm
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
